ALTER TABLE problems ALTER COLUMN body DROP NOT NULL;
ALTER TABLE solutions ALTER COLUMN body DROP NOT NULL;

ALTER TABLE problems ADD COLUMN img_path VARCHAR;
ALTER TABLE solutions ADD COLUMN img_path VARCHAR;
