CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

ALTER TABLE users DROP CONSTRAINT users_pkey CASCADE;
ALTER TABLE users DROP COLUMN id;
ALTER TABLE users ADD COLUMN id UUID NOT NULL DEFAULT uuid_generate_v1();
ALTER TABLE users ADD PRIMARY KEY (id);

ALTER TABLE users ADD COLUMN password VARCHAR;
